[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.ruff]
target-version = "py310"
line-length = 100
select = ["E", "F", "I", "W", "UP", "B", "C4", "ARG", "T20", "PT", "PTH", "SIM", "TRY", "PL", "RUF", "NPY"]
ignore = ["E501"]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.coverage.run]
source = ["src"]
omit = ["*/__pycache__/*", "*/tests/*"]

[tool.hatch.build.targets.wheel]
packages = ["src"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "proav-shoko"
version = "0.4.0-beta.16"
description = "USB analysis tool for AV environments"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "usb-monitor>=1.0.0",
    "screeninfo>=0.8.0",
    "customtkinter>=5.2.0"
]

[project.scripts]
proav-shoko = "src.main:main"